import Head from "next/head";
import { useRouter } from "next/router";
import { Navbar, Footer } from "@components/index";

function Layout(props) {
  const { title, children } = props;
  const router = useRouter();

  return (
    <div className=" font-inter">
      <Head>
        <title>{title} | Bukabiz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`${router.basePath}/favicon.png`} />
      </Head>
      {/* <Navbar /> */}
      {children}
      <Footer />
    </div>
  );
}
export default Layout;
