import Head from 'next/head'
import dynamic from 'next/dynamic'
import { useRouter } from 'next/router'
import { Footer } from '@components/index'

const Navbar = dynamic(
  () => import('../components/Navbar'),
  { ssr: false },
)

function Layout(props) {
  const { title, children } = props
  const router = useRouter()

  return (
    <div className=" font-inter">
      <Head>
        <title>{title} | Bukabiz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={`${router.basePath}/favicon.png`} />
      </Head>
      <Navbar />
      {children}
      <Footer />
    </div>
  )
}
export default Layout